# Generated by Django 5.1.1 on 2024-09-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('author', 'Can modify books')]},
        ),
    ]
